[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
accountability = "4wJH64VGkp4kLPMFGU9p9q2cLKjThDsUaYY2WAJS7jJ9"

[programs.localnet]
accountability = "4wJH64VGkp4kLPMFGU9p9q2cLKjThDsUaYY2WAJS7jJ9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = ".wallets/deployer.json"

[scripts]
test = "npm run test:anchor"
